repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.0
  hooks:
    # Run the linter
    - id: ruff-check
      args:
        - --fix
        - --all-files
    # Run the formatter.
    - id: ruff-format
      args:
        - --all-files
